### ISSUE TITLE
Error sometimes when starting Veeam services

### ISSUE THREAD

**Issue by carceneaux** [VeeamHub/veeam-ansible#36]
Receiving the following error sometimes:

`non-zero return code`

![CleanShot 2023-02-15 at 09 18 20](https://user-images.githubusercontent.com/17179966/219052750-bbbad5ea-8e4d-4d82-8bcb-df8a82acc229.png)

When executing the following Ansible code:

```yaml
- name: Ensure Veeam services are running
  ansible.windows.win_shell: |
    Get-Service veeam* | Start-Service -ErrorAction SilentlyContinue
```

While I'd expect the `ErrorAction` param to negate this behavior, this is not the case. Need to update code to the following to resolve this issue:

```yaml
- name: Ensure Veeam services are running
  ansible.windows.win_shell: |
    Get-Service veeam* | Where-Object {$_.Name -ne "VeeamMBPDeploymentService"} | Start-Service
```
