### ISSUE TITLE
Ansible playbook gets error while installing community edition v12 with or without ISO

### ISSUE THREAD

**Issue by bharath8671** [VeeamHub/veeam-ansible#43]
**Describe the bug**
When I run the playbook using roles from VeeamHub and used playbook with ISO download and installing community version of veeam and with out ISO download and installing community edition of Veeam Backup and Replication

**To Reproduce**
Installled roles - VeeamHub from ansible-galaxy
used the playbook from github 
---
- name: Veeam Backup & Replication Install
  hosts: all
  tasks:
    - name: Copy Veeam ISO file to Windows
      copy:
        src: "/XXXX/VeeamBackup&Replication_12.0.0.1420_20230209.iso"
        dest: "C:\\Downloads\\"

    - include_role:
        name: veeamhub.veeam.veeam_vas
        tasks_from: vbr_install
      vars:
        version: "12"
        destination: "C:\\Downloads\\"
        destination_iso_file: "VeeamBackup&Replication_12.0.0.1420_20230209.iso"
        sql_install_username: "sql_install"
        sql_install_password: "PassW0rd!"
        sql_service_username: "svc_sql"
        sql_service_password: "PassW0rd!"
        sql_username: "sa"
        sql_password: "PassW0rd!"

**Screenshots**

![image](https://user-images.githubusercontent.com/120463306/230911890-9079e880-dea0-4bfb-99c5-b7ab2a93ca1c.png)

Operating system used for Veeam Installation
 - OS: Windows server 2019
 
Could anyone solve this issue

**Comment by bharath8671** [comment]
Thank you for your help
I'm using this code from the repo - https://github.com/VeeamHub/veeam-ansible/tree/master/roles/veeam_vas#veeam-backup--replication-community-edition-install-without-iso-download
which is why I get that error I think.

**Comment by kbreit-insight** [comment]
I am seeing this error even though I am specifying `postgres`. This is copied from the documentation so the credentials should look familiar. Windows 2022 Server and Veeam 12.

```
- name: Install Veeam Backup & Recovery
  hosts: all
  tasks:
    - include_role:
        name: veeamhub.veeam.veeam_vas
        tasks_from: vbr_install
      vars:
        version: "12"
        iso_download: true
        sql_install_username: "sql_install"
        sql_install_password: "ChangeM3!"
        sql_service_username: "svc_sql"
        sql_service_password: "ChangeM3!"
        sql_username: "postgres"
        sql_password: "ChangeM3!"
        license: true
        source_license: licenses/vrb.lic
        iso_download: false
        # https://docs.ansible.com/ansible/latest/user_guide/playbooks_vault.html#single-encrypted-variable
    - name: Applying tuning on a local PostgreSQL server running as the VBR DB
      veeamhub.veeam.veeam_vbr_set_postgres_database_server_limits:
```
