### ISSUE TITLE
Add Auto Reboot var 

### ISSUE THREAD

**Issue by mritsurgeon** [VeeamHub/veeam-ansible#56]
install_VBR.yml

```yaml
- name: Checking OS for pending reboots
  block:
    - name: "Check for pending reboots"
      pending_reboot_check:
      register: precheck
      failed_when: "(precheck.pending_reboot | bool) and (auto_reboot == 'no')"

- name: Handle pending reboots and initiate reboot if necessary
  block:
    - name: "Reboot if necessary"
      ansible.windows.win_reboot:
        test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'
      retries: 5
      delay: 60
      when: precheck.pending_reboot | bool
  when: precheck.pending_reboot | bool
```
Example Playbook : 

```yaml
- name: Veeam Backup & Replication Install
  hosts: vbr
  tasks:
    - include_role:
        name: veeamhub.veeam.veeam_vas
        tasks_from: vbr_install
      vars:
        version: "12"
        auto_reboot: "yes"
        sql_install_username: 'sql_install'
        sql_install_password: 'windows_password'
        sql_service_username: 'svc_sql'
        sql_service_password: 'windows_password'
        sql_username: 'postgres'
        sql_password: 'linux_password'
```

**Comment by mritsurgeon** [comment]
Automatically rebooting server then waiting for it to be available and then starting with next task , all controlled via one playbook run , as the example I shared which I modified to use , I’m running a UI that’s calling playbook in backend & passing variables , without auto reboot I’ll have to code a reboot button in UI. Simple Boolean Syntax can be passed to playbook through a tick box. 

If a server needs reboot now you need to manually reboot it & the rerun playbook, what I suggested and sample is playbook initiates reboot then waits then continues.

**Comment by carceneaux** [comment]
Thanks for the additional info.

So in most places in collection a reboot already occurs when needed. The only exception to that is in the [pre-checks](https://github.com/VeeamHub/veeam-ansible/blob/master/roles/veeam_vas/tasks/vbr_install.yml#L3-L10).

I left this at a fail as I expected the user to code to check for a pending reboot before initiating an install/upgrade to their Veeam environment. I was hesitant to include an automatic reboot here at the beginning in case jobs are still running or there is some other unforeseen environment change. For example, if someone had neglected to reboot after Windows updates, the reboot could take quite some time.

For the time being, I recommend checking for a pending reboot prior to executing a Veeam install/upgrade.

**Comment by carceneaux** [comment]
Quick update for anyone wanting to do the same. This collection has a module to assist with this effort. If you'd like to check for pending reboots and reboot prior to upgrade in an automated fashion, add the following tasks to your playbook:

```yaml
    - name: Checking OS for pending reboots
      veeamhub.veeam.pending_reboot_check:
      register: check
    - name: Rebooting server if necessary
      ansible.windows.win_reboot:
        msg: Reboot initiated by Ansible as requested by pending reboot check.
      when: check.pending_reboot | bool
```
